spring:
  application:
    name: post-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){blue} %clr(%-5level){desc} %clr(%logger{36}){cyan}: %msg%n"
  level-expressions:
      level-config:
        ERROR: red
        WARN: yellow
        INFO: green
        DEBUG: blue